---
title: "Preregistration: Changes"
output:
  html_document:
    toc: TRUE
    toc_float:
      collapsed: FALSE
      toc_depth: 3
---
  
The following changes were introduced after the preregistration.

## Wording Hypotheses

Before: Hypothesis: The within-person effects of all types of COVID-19 related social media use on all types of well-being indicators---while controlling for several stable and varying covariates such as sociodemographic variables and psychological dispositions---will be trivial.

Now: "Hypothesis: The within-person effects of all measures of COVID-19 related social media use (types: reading, liking and sharing, posting; channels: Twitter, Instagram, Facebook, YouTube, WhatsApp) on all measures of well-being indicators (positive affect, negative affect, life satisfaction)---while controlling for several stable and varying covariates such as sociodemographic variables and psychological dispositions (see below)---will be trivial.

Explanation: The wording of the hypotheses was extended to be more precise. In addition, I link to the control variables explicated below.

## Covariates

I originally planned to include the following variables as varying covariates. I thought they were measured at several/all waves. However, upon seeing the actual data I realized this wasn't the case. I hence included them as stable covariates.

This includes residency is Vienna, self-reported physical health, living space (in squaremeter), access to balcony, access to garden, and employment status.

I additionally planned to control for satisfaction with democracy and other types of media use. However, it's likely that they also serve as mediators, which is why I will not include them in the main models. They will, however, be reported in the supplementary analyses.


## Imputation

After having received feedback from colleagues who are experts on missing data analyses, I changed the imputation strategy.

- Before: predictive mean matching with n = 1 data-sets; now: multiple imputation (also predictive mean matching) with n = 5 data-sets.
- Before: remove participants with > 50% missing data; now: include all participants

## Estimation

Positive affect and negative affect were modeled as mean scores and not as factor scores. The reason was that it wasn't possible to extract factor scores for the data set with multiple imputation.